/// @macro {Real}
#macro D3D11_INPUT_PER_VERTEX_DATA 0
/// @macro {Real}
#macro D3D11_INPUT_PER_INSTANCE_DATA 1

/// @macro {Real}
#macro D3D11_FILL_WIREFRAME 2
/// @macro {Real}
#macro D3D11_FILL_SOLID 3

/// @macro {Real}
#macro D3D11_CULL_NONE 1
/// @macro {Real}
#macro D3D11_CULL_FRONT 2
/// @macro {Real}
#macro D3D11_CULL_BACK 3

/// @macro {Real}
#macro D3D11_RESOURCE_DIMENSION_UNKNOWN 0
/// @macro {Real}
#macro D3D11_RESOURCE_DIMENSION_BUFFER 1
/// @macro {Real}
#macro D3D11_RESOURCE_DIMENSION_TEXTURE1D 2
/// @macro {Real}
#macro D3D11_RESOURCE_DIMENSION_TEXTURE2D 3
/// @macro {Real}
#macro D3D11_RESOURCE_DIMENSION_TEXTURE3D 4

/// @macro {Real}
#macro D3D11_DSV_DIMENSION_UNKNOWN 0
/// @macro {Real}
#macro D3D11_DSV_DIMENSION_TEXTURE1D 1
/// @macro {Real}
#macro D3D11_DSV_DIMENSION_TEXTURE1DARRAY 2
/// @macro {Real}
#macro D3D11_DSV_DIMENSION_TEXTURE2D 3
/// @macro {Real}
#macro D3D11_DSV_DIMENSION_TEXTURE2DARRAY 4
/// @macro {Real}
#macro D3D11_DSV_DIMENSION_TEXTURE2DMS 5
/// @macro {Real}
#macro D3D11_DSV_DIMENSION_TEXTURE2DMSARRAY 6

/// @macro {Real}
#macro D3D11_RTV_DIMENSION_UNKNOWN 0
/// @macro {Real}
#macro D3D11_RTV_DIMENSION_BUFFER 1
/// @macro {Real}
#macro D3D11_RTV_DIMENSION_TEXTURE1D 2
/// @macro {Real}
#macro D3D11_RTV_DIMENSION_TEXTURE1DARRAY 3
/// @macro {Real}
#macro D3D11_RTV_DIMENSION_TEXTURE2D 4
/// @macro {Real}
#macro D3D11_RTV_DIMENSION_TEXTURE2DARRAY 5
/// @macro {Real}
#macro D3D11_RTV_DIMENSION_TEXTURE2DMS 6
/// @macro {Real}
#macro D3D11_RTV_DIMENSION_TEXTURE2DMSARRAY 7
/// @macro {Real}
#macro D3D11_RTV_DIMENSION_TEXTURE3D 8

/// @macro {Real}
#macro D3D11_UAV_DIMENSION_UNKNOWN 0
/// @macro {Real}
#macro D3D11_UAV_DIMENSION_BUFFER 1
/// @macro {Real}
#macro D3D11_UAV_DIMENSION_TEXTURE1D 2
/// @macro {Real}
#macro D3D11_UAV_DIMENSION_TEXTURE1DARRAY 3
/// @macro {Real}
#macro D3D11_UAV_DIMENSION_TEXTURE2D 4
/// @macro {Real}
#macro D3D11_UAV_DIMENSION_TEXTURE2DARRAY 5
/// @macro {Real}
#macro D3D11_UAV_DIMENSION_TEXTURE3D 8

/// @macro {Real}
#macro D3D11_USAGE_DEFAULT 0
/// @macro {Real}
#macro D3D11_USAGE_IMMUTABLE 1
/// @macro {Real}
#macro D3D11_USAGE_DYNAMIC 2
/// @macro {Real}
#macro D3D11_USAGE_STAGING 3

/// @macro {Real}
#macro D3D11_BIND_VERTEX_BUFFER 0x1
/// @macro {Real}
#macro D3D11_BIND_INDEX_BUFFER 0x2
/// @macro {Real}
#macro D3D11_BIND_CONSTANT_BUFFER 0x4
/// @macro {Real}
#macro D3D11_BIND_SHADER_RESOURCE 0x8
/// @macro {Real}
#macro D3D11_BIND_STREAM_OUTPUT 0x10
/// @macro {Real}
#macro D3D11_BIND_RENDER_TARGET 0x20
/// @macro {Real}
#macro D3D11_BIND_DEPTH_STENCIL 0x40
/// @macro {Real}
#macro D3D11_BIND_UNORDERED_ACCESS 0x80
/// @macro {Real}
#macro D3D11_BIND_DECODER 0x200
/// @macro {Real}
#macro D3D11_BIND_VIDEO_ENCODER 0x400

/// @macro {Real}
#macro D3D11_CPU_ACCESS_WRITE 0x10000
/// @macro {Real}
#macro D3D11_CPU_ACCESS_READ 0x20000

/// @macro {Real}
#macro D3D11_RESOURCE_MISC_GENERATE_MIPS 0x1
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_SHARED 0x2
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_TEXTURECUBE 0x4
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_DRAWINDIRECT_ARGS 0x10
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_BUFFER_ALLOW_RAW_VIEWS 0x20
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_BUFFER_STRUCTURED 0x40
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_RESOURCE_CLAMP 0x80
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_SHARED_KEYEDMUTEX 0x100
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_GDI_COMPATIBLE 0x200
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_SHARED_NTHANDLE 0x800
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_RESTRICTED_CONTENT 0x1000
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_RESTRICT_SHARED_RESOURCE 0x2000
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_RESTRICT_SHARED_RESOURCE_DRIVER 0x4000
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_GUARDED 0x8000
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_TILE_POOL 0x20000
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_TILED 0x40000
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_HW_PROTECTED 0x80000
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_SHARED_DISPLAYABLE 0x100000
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_SHARED_EXCLUSIVE_WRITER 0x200000
/// @macro {Real}
#macro D3D11_RESOURCE_MISC_NO_SHADER_ACCESS 0x400000

/// @macro {Real}
#macro D3D11_MAP_READ 1
/// @macro {Real}
#macro D3D11_MAP_WRITE 2
/// @macro {Real}
#macro D3D11_MAP_READ_WRITE 3
/// @macro {Real}
#macro D3D11_MAP_WRITE_DISCARD 4
/// @macro {Real}
#macro D3D11_MAP_WRITE_NO_OVERWRITE 5

/// @macro {Real}
#macro D3D11_MAP_FLAG_DO_NOT_WAIT 0x100000

/// @macro {Real}
#macro D3D11_RAISE_FLAG_DRIVER_INTERNAL_ERROR 0x1

/// @macro {Real}
#macro D3D11_CLEAR_DEPTH 0x1
/// @macro {Real}
#macro D3D11_CLEAR_STENCIL 0x2

/// @macro {Real}
#macro D3D11_COMPARISON_NEVER 1
/// @macro {Real}
#macro D3D11_COMPARISON_LESS 2
/// @macro {Real}
#macro D3D11_COMPARISON_EQUAL 3
/// @macro {Real}
#macro D3D11_COMPARISON_LESS_EQUAL 4
/// @macro {Real}
#macro D3D11_COMPARISON_GREATER 5
/// @macro {Real}
#macro D3D11_COMPARISON_NOT_EQUAL 6
/// @macro {Real}
#macro D3D11_COMPARISON_GREATER_EQUAL 7
/// @macro {Real}
#macro D3D11_COMPARISON_ALWAYS 8

/// @macro {Real}
#macro D3D11_DEPTH_WRITE_MASK_ZERO 0
/// @macro {Real}
#macro D3D11_DEPTH_WRITE_MASK_ALL 1

/// @macro {Real}
#macro D3D11_STENCIL_OP_KEEP 1
/// @macro {Real}
#macro D3D11_STENCIL_OP_ZERO 2
/// @macro {Real}
#macro D3D11_STENCIL_OP_REPLACE 3
/// @macro {Real}
#macro D3D11_STENCIL_OP_INCR_SAT 4
/// @macro {Real}
#macro D3D11_STENCIL_OP_DECR_SAT 5
/// @macro {Real}
#macro D3D11_STENCIL_OP_INVERT 6
/// @macro {Real}
#macro D3D11_STENCIL_OP_INCR 7
/// @macro {Real}
#macro D3D11_STENCIL_OP_DECR 8

/// @macro {Real}
#macro D3D11_BLEND_ZERO 1
/// @macro {Real}
#macro D3D11_BLEND_ONE 2
/// @macro {Real}
#macro D3D11_BLEND_SRC_COLOR 3
/// @macro {Real}
#macro D3D11_BLEND_INV_SRC_COLOR 4
/// @macro {Real}
#macro D3D11_BLEND_SRC_ALPHA 5
/// @macro {Real}
#macro D3D11_BLEND_INV_SRC_ALPHA 6
/// @macro {Real}
#macro D3D11_BLEND_DEST_ALPHA 7
/// @macro {Real}
#macro D3D11_BLEND_INV_DEST_ALPHA 8
/// @macro {Real}
#macro D3D11_BLEND_DEST_COLOR 9
/// @macro {Real}
#macro D3D11_BLEND_INV_DEST_COLOR 10
/// @macro {Real}
#macro D3D11_BLEND_SRC_ALPHA_SAT 11
/// @macro {Real}
#macro D3D11_BLEND_BLEND_FACTOR 14
/// @macro {Real}
#macro D3D11_BLEND_INV_BLEND_FACTOR 15
/// @macro {Real}
#macro D3D11_BLEND_SRC1_COLOR 16
/// @macro {Real}
#macro D3D11_BLEND_INV_SRC1_COLOR 17
/// @macro {Real}
#macro D3D11_BLEND_SRC1_ALPHA 18
/// @macro {Real}
#macro D3D11_BLEND_INV_SRC1_ALPHA 19

/// @macro {Real}
#macro D3D11_BLEND_OP_ADD 1
/// @macro {Real}
#macro D3D11_BLEND_OP_SUBTRACT 2
/// @macro {Real}
#macro D3D11_BLEND_OP_REV_SUBTRACT 3
/// @macro {Real}
#macro D3D11_BLEND_OP_MIN 4
/// @macro {Real}
#macro D3D11_BLEND_OP_MAX 5

/// @macro {Real}
#macro D3D11_COLOR_WRITE_ENABLE_RED 1
/// @macro {Real}
#macro D3D11_COLOR_WRITE_ENABLE_GREEN 2
/// @macro {Real}
#macro D3D11_COLOR_WRITE_ENABLE_BLUE 4
/// @macro {Real}
#macro D3D11_COLOR_WRITE_ENABLE_ALPHA 8
/// @macro {Real}
#macro D3D11_COLOR_WRITE_ENABLE_ALL ( ( ( D3D11_COLOR_WRITE_ENABLE_RED | D3D11_COLOR_WRITE_ENABLE_GREEN )  | D3D11_COLOR_WRITE_ENABLE_BLUE )  | D3D11_COLOR_WRITE_ENABLE_ALPHA )

/// @macro {Real}
#macro D3D11_TEXTURECUBE_FACE_POSITIVE_X 0
/// @macro {Real}
#macro D3D11_TEXTURECUBE_FACE_NEGATIVE_X 1
/// @macro {Real}
#macro D3D11_TEXTURECUBE_FACE_POSITIVE_Y 2
/// @macro {Real}
#macro D3D11_TEXTURECUBE_FACE_NEGATIVE_Y 3
/// @macro {Real}
#macro D3D11_TEXTURECUBE_FACE_POSITIVE_Z 4
/// @macro {Real}
#macro D3D11_TEXTURECUBE_FACE_NEGATIVE_Z 5

/// @macro {Real}
#macro D3D11_BUFFEREX_SRV_FLAG_RAW 0x1

/// @macro {Real}
#macro D3D11_DSV_READ_ONLY_DEPTH 0x1
/// @macro {Real}
#macro D3D11_DSV_READ_ONLY_STENCIL 0x2

/// @macro {Real}
#macro D3D11_BUFFER_UAV_FLAG_RAW 0x1
/// @macro {Real}
#macro D3D11_BUFFER_UAV_FLAG_APPEND 0x2
/// @macro {Real}
#macro D3D11_BUFFER_UAV_FLAG_COUNTER 0x4

/// @macro {Real}
#macro D3D11_FILTER_MIN_MAG_MIP_POINT 0
/// @macro {Real}
#macro D3D11_FILTER_MIN_MAG_POINT_MIP_LINEAR 0x1
/// @macro {Real}
#macro D3D11_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT 0x4
/// @macro {Real}
#macro D3D11_FILTER_MIN_POINT_MAG_MIP_LINEAR 0x5
/// @macro {Real}
#macro D3D11_FILTER_MIN_LINEAR_MAG_MIP_POINT 0x10
/// @macro {Real}
#macro D3D11_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR 0x11
/// @macro {Real}
#macro D3D11_FILTER_MIN_MAG_LINEAR_MIP_POINT 0x14
/// @macro {Real}
#macro D3D11_FILTER_MIN_MAG_MIP_LINEAR 0x15
/// @macro {Real}
#macro D3D11_FILTER_ANISOTROPIC 0x55
/// @macro {Real}
#macro D3D11_FILTER_COMPARISON_MIN_MAG_MIP_POINT 0x80
/// @macro {Real}
#macro D3D11_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR 0x81
/// @macro {Real}
#macro D3D11_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT 0x84
/// @macro {Real}
#macro D3D11_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR 0x85
/// @macro {Real}
#macro D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT 0x90
/// @macro {Real}
#macro D3D11_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR 0x91
/// @macro {Real}
#macro D3D11_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT 0x94
/// @macro {Real}
#macro D3D11_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR 0x95
/// @macro {Real}
#macro D3D11_FILTER_COMPARISON_ANISOTROPIC 0xd5
/// @macro {Real}
#macro D3D11_FILTER_MINIMUM_MIN_MAG_MIP_POINT 0x100
/// @macro {Real}
#macro D3D11_FILTER_MINIMUM_MIN_MAG_POINT_MIP_LINEAR 0x101
/// @macro {Real}
#macro D3D11_FILTER_MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT 0x104
/// @macro {Real}
#macro D3D11_FILTER_MINIMUM_MIN_POINT_MAG_MIP_LINEAR 0x105
/// @macro {Real}
#macro D3D11_FILTER_MINIMUM_MIN_LINEAR_MAG_MIP_POINT 0x110
/// @macro {Real}
#macro D3D11_FILTER_MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR 0x111
/// @macro {Real}
#macro D3D11_FILTER_MINIMUM_MIN_MAG_LINEAR_MIP_POINT 0x114
/// @macro {Real}
#macro D3D11_FILTER_MINIMUM_MIN_MAG_MIP_LINEAR 0x115
/// @macro {Real}
#macro D3D11_FILTER_MINIMUM_ANISOTROPIC 0x155
/// @macro {Real}
#macro D3D11_FILTER_MAXIMUM_MIN_MAG_MIP_POINT 0x180
/// @macro {Real}
#macro D3D11_FILTER_MAXIMUM_MIN_MAG_POINT_MIP_LINEAR 0x181
/// @macro {Real}
#macro D3D11_FILTER_MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT 0x184
/// @macro {Real}
#macro D3D11_FILTER_MAXIMUM_MIN_POINT_MAG_MIP_LINEAR 0x185
/// @macro {Real}
#macro D3D11_FILTER_MAXIMUM_MIN_LINEAR_MAG_MIP_POINT 0x190
/// @macro {Real}
#macro D3D11_FILTER_MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR 0x191
/// @macro {Real}
#macro D3D11_FILTER_MAXIMUM_MIN_MAG_LINEAR_MIP_POINT 0x194
/// @macro {Real}
#macro D3D11_FILTER_MAXIMUM_MIN_MAG_MIP_LINEAR 0x195
/// @macro {Real}
#macro D3D11_FILTER_MAXIMUM_ANISOTROPIC 0x1d5

/// @macro {Real}
#macro D3D11_FILTER_TYPE_POINT 0
/// @macro {Real}
#macro D3D11_FILTER_TYPE_LINEAR 1

/// @macro {Real}
#macro D3D11_FILTER_REDUCTION_TYPE_STANDARD 0
/// @macro {Real}
#macro D3D11_FILTER_REDUCTION_TYPE_COMPARISON 1
/// @macro {Real}
#macro D3D11_FILTER_REDUCTION_TYPE_MINIMUM 2
/// @macro {Real}
#macro D3D11_FILTER_REDUCTION_TYPE_MAXIMUM 3

/// @macro {Real}
#macro D3D11_TEXTURE_ADDRESS_WRAP 1
/// @macro {Real}
#macro D3D11_TEXTURE_ADDRESS_MIRROR 2
/// @macro {Real}
#macro D3D11_TEXTURE_ADDRESS_CLAMP 3
/// @macro {Real}
#macro D3D11_TEXTURE_ADDRESS_BORDER 4
/// @macro {Real}
#macro D3D11_TEXTURE_ADDRESS_MIRROR_ONCE 5

/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_BUFFER 0x1
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_IA_VERTEX_BUFFER 0x2
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_IA_INDEX_BUFFER 0x4
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_SO_BUFFER 0x8
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_TEXTURE1D 0x10
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_TEXTURE2D 0x20
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_TEXTURE3D 0x40
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_TEXTURECUBE 0x80
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_SHADER_LOAD 0x100
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_SHADER_SAMPLE 0x200
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_SHADER_SAMPLE_COMPARISON 0x400
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_SHADER_SAMPLE_MONO_TEXT 0x800
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_MIP 0x1000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_MIP_AUTOGEN 0x2000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_RENDER_TARGET 0x4000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_BLENDABLE 0x8000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_DEPTH_STENCIL 0x10000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_CPU_LOCKABLE 0x20000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_MULTISAMPLE_RESOLVE 0x40000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_DISPLAY 0x80000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_CAST_WITHIN_BIT_LAYOUT 0x100000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_MULTISAMPLE_RENDERTARGET 0x200000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_MULTISAMPLE_LOAD 0x400000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_SHADER_GATHER 0x800000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_BACK_BUFFER_CAST 0x1000000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_TYPED_UNORDERED_ACCESS_VIEW 0x2000000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_SHADER_GATHER_COMPARISON 0x4000000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_DECODER_OUTPUT 0x8000000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_VIDEO_PROCESSOR_OUTPUT 0x10000000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_VIDEO_PROCESSOR_INPUT 0x20000000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT_VIDEO_ENCODER 0x40000000

/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT2_UAV_ATOMIC_ADD 0x1
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT2_UAV_ATOMIC_BITWISE_OPS 0x2
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT2_UAV_ATOMIC_COMPARE_STORE_OR_COMPARE_EXCHANGE 0x4
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT2_UAV_ATOMIC_EXCHANGE 0x8
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT2_UAV_ATOMIC_SIGNED_MIN_OR_MAX 0x10
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT2_UAV_ATOMIC_UNSIGNED_MIN_OR_MAX 0x20
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT2_UAV_TYPED_LOAD 0x40
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT2_UAV_TYPED_STORE 0x80
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT2_OUTPUT_MERGER_LOGIC_OP 0x100
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT2_TILED 0x200
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT2_SHAREABLE 0x400
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT2_MULTIPLANE_OVERLAY 0x4000
/// @macro {Real}
#macro D3D11_FORMAT_SUPPORT2_DISPLAYABLE 0x10000

/// @macro {Real}
#macro D3D11_ASYNC_GETDATA_DONOTFLUSH 0x1

/// @macro {Real}
#macro D3D11_QUERY_EVENT 0
/// @macro {Real}
#macro D3D11_QUERY_OCCLUSION ( D3D11_QUERY_EVENT + 1 )
/// @macro {Real}
#macro D3D11_QUERY_TIMESTAMP ( D3D11_QUERY_OCCLUSION + 1 )
/// @macro {Real}
#macro D3D11_QUERY_TIMESTAMP_DISJOINT ( D3D11_QUERY_TIMESTAMP + 1 )
/// @macro {Real}
#macro D3D11_QUERY_PIPELINE_STATISTICS ( D3D11_QUERY_TIMESTAMP_DISJOINT + 1 )
/// @macro {Real}
#macro D3D11_QUERY_OCCLUSION_PREDICATE ( D3D11_QUERY_PIPELINE_STATISTICS + 1 )
/// @macro {Real}
#macro D3D11_QUERY_SO_STATISTICS ( D3D11_QUERY_OCCLUSION_PREDICATE + 1 )
/// @macro {Real}
#macro D3D11_QUERY_SO_OVERFLOW_PREDICATE ( D3D11_QUERY_SO_STATISTICS + 1 )
/// @macro {Real}
#macro D3D11_QUERY_SO_STATISTICS_STREAM0 ( D3D11_QUERY_SO_OVERFLOW_PREDICATE + 1 )
/// @macro {Real}
#macro D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM0 ( D3D11_QUERY_SO_STATISTICS_STREAM0 + 1 )
/// @macro {Real}
#macro D3D11_QUERY_SO_STATISTICS_STREAM1 ( D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM0 + 1 )
/// @macro {Real}
#macro D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM1 ( D3D11_QUERY_SO_STATISTICS_STREAM1 + 1 )
/// @macro {Real}
#macro D3D11_QUERY_SO_STATISTICS_STREAM2 ( D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM1 + 1 )
/// @macro {Real}
#macro D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM2 ( D3D11_QUERY_SO_STATISTICS_STREAM2 + 1 )
/// @macro {Real}
#macro D3D11_QUERY_SO_STATISTICS_STREAM3 ( D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM2 + 1 )
/// @macro {Real}
#macro D3D11_QUERY_SO_OVERFLOW_PREDICATE_STREAM3 ( D3D11_QUERY_SO_STATISTICS_STREAM3 + 1 )

/// @macro {Real}
#macro D3D11_QUERY_MISC_PREDICATEHINT 0x1

/// @macro {Real}
#macro D3D11_COUNTER_DEVICE_DEPENDENT_0 0x40000000

/// @macro {Real}
#macro D3D11_COUNTER_TYPE_FLOAT32 0
/// @macro {Real}
#macro D3D11_COUNTER_TYPE_UINT16 ( D3D11_COUNTER_TYPE_FLOAT32 + 1 )
/// @macro {Real}
#macro D3D11_COUNTER_TYPE_UINT32 ( D3D11_COUNTER_TYPE_UINT16 + 1 )
/// @macro {Real}
#macro D3D11_COUNTER_TYPE_UINT64 ( D3D11_COUNTER_TYPE_UINT32 + 1 )

/// @macro {Real}
#macro D3D11_STANDARD_MULTISAMPLE_PATTERN 0xffffffff
/// @macro {Real}
#macro D3D11_CENTER_MULTISAMPLE_PATTERN 0xfffffffe

/// @macro {Real}
#macro D3D11_DEVICE_CONTEXT_IMMEDIATE 0
/// @macro {Real}
#macro D3D11_DEVICE_CONTEXT_DEFERRED ( D3D11_DEVICE_CONTEXT_IMMEDIATE + 1 )

/// @macro {Real}
#macro D3D11_FEATURE_THREADING 0
/// @macro {Real}
#macro D3D11_FEATURE_DOUBLES ( D3D11_FEATURE_THREADING + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_FORMAT_SUPPORT ( D3D11_FEATURE_DOUBLES + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_FORMAT_SUPPORT2 ( D3D11_FEATURE_FORMAT_SUPPORT + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_D3D10_X_HARDWARE_OPTIONS ( D3D11_FEATURE_FORMAT_SUPPORT2 + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_D3D11_OPTIONS ( D3D11_FEATURE_D3D10_X_HARDWARE_OPTIONS + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_ARCHITECTURE_INFO ( D3D11_FEATURE_D3D11_OPTIONS + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_D3D9_OPTIONS ( D3D11_FEATURE_ARCHITECTURE_INFO + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_SHADER_MIN_PRECISION_SUPPORT ( D3D11_FEATURE_D3D9_OPTIONS + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_D3D9_SHADOW_SUPPORT ( D3D11_FEATURE_SHADER_MIN_PRECISION_SUPPORT + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_D3D11_OPTIONS1 ( D3D11_FEATURE_D3D9_SHADOW_SUPPORT + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_D3D9_SIMPLE_INSTANCING_SUPPORT ( D3D11_FEATURE_D3D11_OPTIONS1 + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_MARKER_SUPPORT ( D3D11_FEATURE_D3D9_SIMPLE_INSTANCING_SUPPORT + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_D3D9_OPTIONS1 ( D3D11_FEATURE_MARKER_SUPPORT + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_D3D11_OPTIONS2 ( D3D11_FEATURE_D3D9_OPTIONS1 + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_D3D11_OPTIONS3 ( D3D11_FEATURE_D3D11_OPTIONS2 + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_GPU_VIRTUAL_ADDRESS_SUPPORT ( D3D11_FEATURE_D3D11_OPTIONS3 + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_D3D11_OPTIONS4 ( D3D11_FEATURE_GPU_VIRTUAL_ADDRESS_SUPPORT + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_SHADER_CACHE ( D3D11_FEATURE_D3D11_OPTIONS4 + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_D3D11_OPTIONS5 ( D3D11_FEATURE_SHADER_CACHE + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_DISPLAYABLE ( D3D11_FEATURE_D3D11_OPTIONS5 + 1 )
/// @macro {Real}
#macro D3D11_FEATURE_D3D11_OPTIONS6 ( D3D11_FEATURE_DISPLAYABLE + 1 )

/// @macro {Real}
#macro D3D11_SHADER_MIN_PRECISION_10_BIT 0x1
/// @macro {Real}
#macro D3D11_SHADER_MIN_PRECISION_16_BIT 0x2

/// @macro {Real}
#macro D3D11_TILED_RESOURCES_NOT_SUPPORTED 0
/// @macro {Real}
#macro D3D11_TILED_RESOURCES_TIER_1 1
/// @macro {Real}
#macro D3D11_TILED_RESOURCES_TIER_2 2
/// @macro {Real}
#macro D3D11_TILED_RESOURCES_TIER_3 3

/// @macro {Real}
#macro D3D11_CONSERVATIVE_RASTERIZATION_NOT_SUPPORTED 0
/// @macro {Real}
#macro D3D11_CONSERVATIVE_RASTERIZATION_TIER_1 1
/// @macro {Real}
#macro D3D11_CONSERVATIVE_RASTERIZATION_TIER_2 2
/// @macro {Real}
#macro D3D11_CONSERVATIVE_RASTERIZATION_TIER_3 3

/// @macro {Real}
#macro D3D11_SHADER_CACHE_SUPPORT_NONE 0
/// @macro {Real}
#macro D3D11_SHADER_CACHE_SUPPORT_AUTOMATIC_INPROC_CACHE 0x1
/// @macro {Real}
#macro D3D11_SHADER_CACHE_SUPPORT_AUTOMATIC_DISK_CACHE 0x2

/// @macro {Real}
#macro D3D11_SHARED_RESOURCE_TIER_0 0
/// @macro {Real}
#macro D3D11_SHARED_RESOURCE_TIER_1 ( D3D11_SHARED_RESOURCE_TIER_0 + 1 )
/// @macro {Real}
#macro D3D11_SHARED_RESOURCE_TIER_2 ( D3D11_SHARED_RESOURCE_TIER_1 + 1 )
/// @macro {Real}
#macro D3D11_SHARED_RESOURCE_TIER_3 ( D3D11_SHARED_RESOURCE_TIER_2 + 1 )

/// @macro {Real}
#macro D3D11_SHADER_ACCESS_RESTRICTED_RESOURCE_TIER_0 0
/// @macro {Real}
#macro D3D11_SHADER_ACCESS_RESTRICTED_RESOURCE_TIER_1 1

/// @macro {Real}
#macro D3D11_VIDEO_DECODER_BUFFER_PICTURE_PARAMETERS 0
/// @macro {Real}
#macro D3D11_VIDEO_DECODER_BUFFER_MACROBLOCK_CONTROL 1
/// @macro {Real}
#macro D3D11_VIDEO_DECODER_BUFFER_RESIDUAL_DIFFERENCE 2
/// @macro {Real}
#macro D3D11_VIDEO_DECODER_BUFFER_DEBLOCKING_CONTROL 3
/// @macro {Real}
#macro D3D11_VIDEO_DECODER_BUFFER_INVERSE_QUANTIZATION_MATRIX 4
/// @macro {Real}
#macro D3D11_VIDEO_DECODER_BUFFER_SLICE_CONTROL 5
/// @macro {Real}
#macro D3D11_VIDEO_DECODER_BUFFER_BITSTREAM 6
/// @macro {Real}
#macro D3D11_VIDEO_DECODER_BUFFER_MOTION_VECTOR 7
/// @macro {Real}
#macro D3D11_VIDEO_DECODER_BUFFER_FILM_GRAIN 8
/// @macro {Real}
#macro D3D11_VIDEO_DECODER_BUFFER_HUFFMAN_TABLE 9

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FORMAT_SUPPORT_INPUT 0x1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FORMAT_SUPPORT_OUTPUT 0x2

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_DEVICE_CAPS_LINEAR_SPACE 0x1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_DEVICE_CAPS_xvYCC 0x2
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_DEVICE_CAPS_RGB_RANGE_CONVERSION 0x4
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_DEVICE_CAPS_YCbCr_MATRIX_CONVERSION 0x8
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_DEVICE_CAPS_NOMINAL_RANGE 0x10

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FEATURE_CAPS_ALPHA_FILL 0x1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FEATURE_CAPS_CONSTRICTION 0x2
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FEATURE_CAPS_LUMA_KEY 0x4
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FEATURE_CAPS_ALPHA_PALETTE 0x8
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FEATURE_CAPS_LEGACY 0x10
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FEATURE_CAPS_STEREO 0x20
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FEATURE_CAPS_ROTATION 0x40
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FEATURE_CAPS_ALPHA_STREAM 0x80
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FEATURE_CAPS_PIXEL_ASPECT_RATIO 0x100
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FEATURE_CAPS_MIRROR 0x200
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FEATURE_CAPS_SHADER_USAGE 0x400
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FEATURE_CAPS_METADATA_HDR10 0x800

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_CAPS_BRIGHTNESS 0x1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_CAPS_CONTRAST 0x2
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_CAPS_HUE 0x4
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_CAPS_SATURATION 0x8
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_CAPS_NOISE_REDUCTION 0x10
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_CAPS_EDGE_ENHANCEMENT 0x20
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_CAPS_ANAMORPHIC_SCALING 0x40
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_CAPS_STEREO_ADJUSTMENT 0x80

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FORMAT_CAPS_RGB_INTERLACED 0x1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FORMAT_CAPS_RGB_PROCAMP 0x2
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FORMAT_CAPS_RGB_LUMA_KEY 0x4
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FORMAT_CAPS_PALETTE_INTERLACED 0x8

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_AUTO_STREAM_CAPS_DENOISE 0x1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_AUTO_STREAM_CAPS_DERINGING 0x2
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_AUTO_STREAM_CAPS_EDGE_ENHANCEMENT 0x4
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_AUTO_STREAM_CAPS_COLOR_CORRECTION 0x8
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_AUTO_STREAM_CAPS_FLESH_TONE_MAPPING 0x10
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_AUTO_STREAM_CAPS_IMAGE_STABILIZATION 0x20
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_AUTO_STREAM_CAPS_SUPER_RESOLUTION 0x40
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_AUTO_STREAM_CAPS_ANAMORPHIC_SCALING 0x80

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_CAPS_MONO_OFFSET 0x1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_CAPS_ROW_INTERLEAVED 0x2
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_CAPS_COLUMN_INTERLEAVED 0x4
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_CAPS_CHECKERBOARD 0x8
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_CAPS_FLIP_MODE 0x10

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_DEINTERLACE_BLEND 0x1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_DEINTERLACE_BOB 0x2
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_DEINTERLACE_ADAPTIVE 0x4
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_DEINTERLACE_MOTION_COMPENSATION 0x8
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_INVERSE_TELECINE 0x10
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_PROCESSOR_CAPS_FRAME_RATE_CONVERSION 0x20

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ITELECINE_CAPS_32 0x1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ITELECINE_CAPS_22 0x2
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ITELECINE_CAPS_2224 0x4
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ITELECINE_CAPS_2332 0x8
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ITELECINE_CAPS_32322 0x10
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ITELECINE_CAPS_55 0x20
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ITELECINE_CAPS_64 0x40
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ITELECINE_CAPS_87 0x80
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ITELECINE_CAPS_222222222223 0x100
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ITELECINE_CAPS_OTHER 0x80000000

/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_SOFTWARE 0x1
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_HARDWARE 0x2
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_PROTECTION_ALWAYS_ON 0x4
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_PARTIAL_DECRYPTION 0x8
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_CONTENT_KEY 0x10
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_FRESHEN_SESSION_KEY 0x20
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_ENCRYPTED_READ_BACK 0x40
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_ENCRYPTED_READ_BACK_KEY 0x80
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_SEQUENTIAL_CTR_IV 0x100
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_ENCRYPT_SLICEDATA_ONLY 0x200
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_DECRYPTION_BLT 0x400
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_PROTECT_UNCOMPRESSED 0x800
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_PROTECTED_MEMORY_PAGEABLE 0x1000
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_TEARDOWN 0x2000
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_DRM_COMMUNICATION 0x4000
/// @macro {Real}
#macro D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_DRM_COMMUNICATION_MULTI_THREADED 0x8000

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_BRIGHTNESS 0
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_CONTRAST 1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_HUE 2
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_SATURATION 3
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_NOISE_REDUCTION 4
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_EDGE_ENHANCEMENT 5
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_ANAMORPHIC_SCALING 6
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_FILTER_STEREO_ADJUSTMENT 7

/// @macro {Real}
#macro D3D11_VIDEO_FRAME_FORMAT_PROGRESSIVE 0
/// @macro {Real}
#macro D3D11_VIDEO_FRAME_FORMAT_INTERLACED_TOP_FIELD_FIRST 1
/// @macro {Real}
#macro D3D11_VIDEO_FRAME_FORMAT_INTERLACED_BOTTOM_FIELD_FIRST 2

/// @macro {Real}
#macro D3D11_VIDEO_USAGE_PLAYBACK_NORMAL 0
/// @macro {Real}
#macro D3D11_VIDEO_USAGE_OPTIMAL_SPEED 1
/// @macro {Real}
#macro D3D11_VIDEO_USAGE_OPTIMAL_QUALITY 2

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_NOMINAL_RANGE_UNDEFINED 0
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_NOMINAL_RANGE_16_235 1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_NOMINAL_RANGE_0_255 2

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ALPHA_FILL_MODE_OPAQUE 0
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ALPHA_FILL_MODE_BACKGROUND 1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ALPHA_FILL_MODE_DESTINATION 2
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ALPHA_FILL_MODE_SOURCE_STREAM 3

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_OUTPUT_RATE_NORMAL 0
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_OUTPUT_RATE_HALF 1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_OUTPUT_RATE_CUSTOM 2

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_FORMAT_MONO 0
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_FORMAT_HORIZONTAL 1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_FORMAT_VERTICAL 2
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_FORMAT_SEPARATE 3
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_FORMAT_MONO_OFFSET 4
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_FORMAT_ROW_INTERLEAVED 5
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_FORMAT_COLUMN_INTERLEAVED 6
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_FORMAT_CHECKERBOARD 7

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_FLIP_NONE 0
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_FLIP_FRAME0 1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_STEREO_FLIP_FRAME1 2

/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ROTATION_IDENTITY 0
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ROTATION_90 1
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ROTATION_180 2
/// @macro {Real}
#macro D3D11_VIDEO_PROCESSOR_ROTATION_270 3

/// @macro {Real}
#macro D3D11_AUTHENTICATED_CHANNEL_D3D11 1
/// @macro {Real}
#macro D3D11_AUTHENTICATED_CHANNEL_DRIVER_SOFTWARE 2
/// @macro {Real}
#macro D3D11_AUTHENTICATED_CHANNEL_DRIVER_HARDWARE 3

/// @macro {Real}
#macro D3D11_PROCESSIDTYPE_UNKNOWN 0
/// @macro {Real}
#macro D3D11_PROCESSIDTYPE_DWM 1
/// @macro {Real}
#macro D3D11_PROCESSIDTYPE_HANDLE 2

/// @macro {Real}
#macro D3D11_BUS_TYPE_OTHER 0
/// @macro {Real}
#macro D3D11_BUS_TYPE_PCI 0x1
/// @macro {Real}
#macro D3D11_BUS_TYPE_PCIX 0x2
/// @macro {Real}
#macro D3D11_BUS_TYPE_PCIEXPRESS 0x3
/// @macro {Real}
#macro D3D11_BUS_TYPE_AGP 0x4
/// @macro {Real}
#macro D3D11_BUS_IMPL_MODIFIER_INSIDE_OF_CHIPSET 0x10000
/// @macro {Real}
#macro D3D11_BUS_IMPL_MODIFIER_TRACKS_ON_MOTHER_BOARD_TO_CHIP 0x20000
/// @macro {Real}
#macro D3D11_BUS_IMPL_MODIFIER_TRACKS_ON_MOTHER_BOARD_TO_SOCKET 0x30000
/// @macro {Real}
#macro D3D11_BUS_IMPL_MODIFIER_DAUGHTER_BOARD_CONNECTOR 0x40000
/// @macro {Real}
#macro D3D11_BUS_IMPL_MODIFIER_DAUGHTER_BOARD_CONNECTOR_INSIDE_OF_NUAE 0x50000
/// @macro {Real}
#macro D3D11_BUS_IMPL_MODIFIER_NON_STANDARD 0x80000000

/// @macro {Real}
#macro D3D11_VDOV_DIMENSION_UNKNOWN 0
/// @macro {Real}
#macro D3D11_VDOV_DIMENSION_TEXTURE2D 1

/// @macro {Real}
#macro D3D11_VPIV_DIMENSION_UNKNOWN 0
/// @macro {Real}
#macro D3D11_VPIV_DIMENSION_TEXTURE2D 1

/// @macro {Real}
#macro D3D11_VPOV_DIMENSION_UNKNOWN 0
/// @macro {Real}
#macro D3D11_VPOV_DIMENSION_TEXTURE2D 1
/// @macro {Real}
#macro D3D11_VPOV_DIMENSION_TEXTURE2DARRAY 2

/// @macro {Real}
#macro D3D11_CREATE_DEVICE_SINGLETHREADED 0x1
/// @macro {Real}
#macro D3D11_CREATE_DEVICE_DEBUG 0x2
/// @macro {Real}
#macro D3D11_CREATE_DEVICE_SWITCH_TO_REF 0x4
/// @macro {Real}
#macro D3D11_CREATE_DEVICE_PREVENT_INTERNAL_THREADING_OPTIMIZATIONS 0x8
/// @macro {Real}
#macro D3D11_CREATE_DEVICE_BGRA_SUPPORT 0x20
/// @macro {Real}
#macro D3D11_CREATE_DEVICE_DEBUGGABLE 0x40
/// @macro {Real}
#macro D3D11_CREATE_DEVICE_PREVENT_ALTERING_LAYER_SETTINGS_FROM_REGISTRY 0x80
/// @macro {Real}
#macro D3D11_CREATE_DEVICE_DISABLE_GPU_TIMEOUT 0x100
/// @macro {Real}
#macro D3D11_CREATE_DEVICE_VIDEO_SUPPORT 0x800
